-
    name: Deployment
    hosts: localhost
    tasks:
  
      - name: stop previous container with same name
        command: docker stop petstore-webapp
        ignore_errors: yes
  
      - name: remove previous container with same name
        command: docker rm petstore-webapp
        ignore_errors: yes
  
      - name: remove previous image with same name
        command: docker rmi mostafaahmed500/finalproject
        ignore_errors: yes
  
      - name: building the image
        command: docker build -t mostafaahmed500/finalproject .
  
      - name: push the image to Docker-hub
        command: docker push mostafaahmed500/finalproject
  
      - name: run a container from pushed image
        command: docker run -d -p 8089:8080 --name petstore-webapp mostafaahmed500/finalproject
